name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Pre-build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/deify/rs_aoc_2024
        cacheFrom: ghcr.io/deify/rs_aoc_2024
        push: always
    
    - name: Build
      uses: devcontainers/ci@v0.3
      with:    
        cacheFrom: ghcr.io/deify/rs_aoc_2024
        push: never
        runCmd: cargo build --verbose
    - name: Run tests
      uses: devcontainers/ci@v0.3
      with:    
        cacheFrom: ghcr.io/deify/rs_aoc_2024
        push: never
        runCmd: cargo test --verbose
    - name: Run AOC benchmark
      uses: devcontainers/ci@v0.3
      with:    
        cacheFrom: ghcr.io/deify/rs_aoc_2024
        push: never
        runCmd: cargo aoc bench
